### ISSUE TITLE
Use of BetterLog directly on script project fails

### ISSUE THREAD

**Issue by jjelosua** [peterherrmann/BetterLog#10]
As said on the README I am trying to use BetterLog inside my project instead of as a Library since google apps scripts says in their documentation that having libraries will make the script a bit slower and I am dealing with a time sensitive task.

When I try to use it copying directly from master to my project and run it I get a `Exceeded maximum stack depth (line 345, file "logging")` error.

I have made a simple example public script:
https://script.google.com/d/1mfX2zDAlhdQJH8naBDX9JffVvs_25CAT2v--RdFGx6ZrSGZ7-I441oiQ/edit?usp=sharing

Left the execution transcript here:
https://gist.github.com/jjelosua/9c524e5f17257b2f186aebe74a2b55f4

**Comment by peterherrmann** [comment]
Thanks for the report @jjelosua, I have reproduced the problem and have a fix in the works. Will post again when it's available.
