### ISSUE TITLE
I'm not sure why, but I get this error - 

### ISSUE THREAD

**Issue by idanb11** [peterherrmann/BetterLog#11]
```
Execution failed: You do not have permission to perform that action. (line 384, file "Code", project "BetterLog") [0.048 seconds total runtime]
```

**Comment by andrewroberts** [comment]
Check you have edit permissions on the sheet you have assigned as your "log" sheet.

**Comment by idanb11** [comment]
I tried setting edit permissions for the entire spreadsheet and I got the
same error.
Should I set the permissions to a specific sheet only?

Thanks for your help.
Idanb11.

**Comment by idanb11** [comment]
still no success...

**Comment by peterherrmann** [comment]
You may need to run one function in the IDE to provoke the initial auth.

**Comment by idanb11** [comment]
Did this and provoked the auth.
Then approved the permissions and I still get the same error like before.
... 🙁

**Comment by peterherrmann** [comment]
Can you make a simplified and publicly reproducible example please?

**Comment by peterherrmann** [comment]
Updated the troubleshooting section in the readme.
