### ISSUE TITLE
Server errors if multiple users quickly writing to log as it tries to refresh

### ISSUE THREAD

**Issue by andrewroberts** [peterherrmann/BetterLog#15]
If I have multiple triggers from multiple users that are writing to a single log sheet when it is trying to do the automatic refresh at 50000 rows SpreadsheetApp throws multiple server errors until I manually delete the contents of the log.

I assume this is because as one trigger is trying to copy the sheet before clearing it, another trigger comes in and tries to do the same thing and they all start blocking each other.

How about adding a "lock" once the refresh is going on?

**Comment by warunasam** [comment]
Having the same issue

**Comment by andrewroberts** [comment]
Looks like there is just test code in Code.gs now.

**Comment by peterherrmann** [comment]
Apologies @andrewroberts - I used a new chrome ext to do the push and it did unexpected things. All good now.

**Comment by andrewroberts** [comment]
Based on my experiments if you use the script lock within a library that lock belongs to the library, not the user of the library. So whilst the library is locked for one user, it is locked for all users. The solution is to pass in the lock object as a parameter to BetterLog.
