### ISSUE TITLE
50000 rollover

### ISSUE THREAD

**Issue by carrickpaul** [peterherrmann/BetterLog#16]
After reaching 50001 lines in the specified google sheet, the log doesn't roll over it creates a new sheet every time the logger is instantiated. This results in a number of sheets with "SheetName as at date-time" and throws an error on line 329 of Code.gs

**Comment by peterherrmann** [comment]
What version of BetterLog are you using @carrickpaul ?

**Comment by carrickpaul** [comment]
admittedly I didn't check the version before removing and re-adding the addon. It was the latest version as of 18 October 2016.

**Comment by peterherrmann** [comment]
There's been a few releases since October so please upgrade to the latest. If the problem reoccurs, then please provide a reproducible example of the problem so we can see further into the problem and hopefully assist.
