### ISSUE TITLE
Cannot handle returning cyclic object.

### ISSUE THREAD

**Issue by cristimocean** [peterherrmann/BetterLog#19]
The library works, but when pasting source code this error pops-up:
"Cannot handle returning cyclic object."

**Comment by peterherrmann** [comment]
Hi, if you can share a reproducible test case I am happy to have a look at it for you.

**Comment by cristimocean** [comment]
Hi thanks for reply. It was something about my code. I could not reproduce that error in a blank sheet. And thanks for the library, it's really helpfull for me as a beginner.

**Comment by peterherrmann** [comment]
Good to hear and good luck!
