### ISSUE TITLE
Permission error when BetterLog is called from a custom function in SS 

### ISSUE THREAD

**Issue by goedtkindt** [peterherrmann/BetterLog#2]
The logging work only when used from within the script editor - but, when a custom function is called from the SS, an error returns as can be seen below: 
![image](https://cloud.githubusercontent.com/assets/4706944/10906296/99f4d864-8220-11e5-9919-18d829c11484.png)

Please provide a solution to grant the correct permissions or explain ?
Many thanks,
Peter

**Comment by andrewroberts** [comment]
I'd imagine this is a limitation of what custom functions can do, either accessing other sheets or something that BetterLog is doing internally. You could try the same functionality (a custom function that makes an entry in another sheet) and see if this gives the same problem. If not must be something BetterLog is doing - and I imagine it does a lot :)

**Comment by peterherrmann** [comment]
Yes, @andrewroberts is correct. In Google Spreadsheets, according to [the docs](https://developers.google.com/apps-script/guides/services/authorization), custom functions run as anonymous users. Unfortunately this means that BetterLog will not be able to edit the spreadsheet to create or append to a log sheet. 

I'm not aware of a workaround but you could write a web app whose URL could be called anonymously with a query parameter that is written to your log.

**Comment by goedtkindt** [comment]
I was indeed looking to for solutions with URL Fetch or JDBC as a possible workaround to create an  "EvenBetterLog" ;-) 
 No time currently ... so I'm inserting temporal returns to see intermediate results while going over my code currently.
I'll close the current issue, but I could suggest the restriction is mentioned in the read me ?
Many thanks Peter & Andrew!

**Comment by peterherrmann** [comment]
Thanks for the report. I've updated the [README](https://github.com/peterherrmann/BetterLog/blob/master/README.md)

**Comment by baerrach** [comment]
I had a slightly different problem.

My custom functions would return the error:

> Error
> You do not have permission to call setValue (line 40).

You still can't log in your custom functions, but I could fix this error by avoiding assigning to the global variable for logger and instead assign it in the onOpen(e) callback. 

If you wanted to use your custom function in google sheet code as well then you could stub out the logger to do nothing.

**Comment by peterherrmann** [comment]
I've done a little dev work on extending logging to custom functions but its been pretty futile trying to work against [the "Loading..." bug(s)](https://code.google.com/p/google-apps-script-issues/issues/detail?id=4156) which are still unresolved but it's looking more promising lately.
