### ISSUE TITLE
When BetterLog is activated onOpen function fails

### ISSUE THREAD

**Issue by profiVideos** [peterherrmann/BetterLog#21]
Hi, I just want to say thank you for developing such an amazing tool.

There is one issue that I noticed.  After enabling BetterLog, code that was in onOpen would no longer run.  In the Google Apps Dashboard, the Head execution shows fail.  If I disable the loading of BetterLog, everything works again.

Here is my code in onOpen;
```
function onOpen() {
   SpreadsheetApp.getUi()
     .createMenu('**> Export Hermes <**')
     .addItem('Add/Update Customer to Master List', 'copyCustomer2Master')
     .addToUi();
};

```
Cheers, Markus

**Comment by andrewroberts** [comment]
What's the error in the "Log > Execution transcript"?

**Comment by profiVideos** [comment]
Mar 23, 2020, 9:29:57 AM
Error
Exception: You do not have permission to call SpreadsheetApp.openById. Required permissions: https://www.googleapis.com/auth/spreadsheets at setLogSheet_(Code:384:38) at useSpreadsheet(Code:43:5)
On 2020-03-23 14:09:38, Andrew Roberts <notifications@github.com> wrote:
What's the error in the "Log > Execution transcript"?

**Comment by andrewroberts** [comment]
There is nothing in your onOpen that would be opening a spreadsheet. You may have added some code that is global and outside any function that is trying to run whenever the sheet is open. You can share you code with me (andrew@roberts.net) if you want me to take a quick look.

**Comment by profiVideos** [comment]
Hi Andrew,

Thanks for your reply.

I should have mentioned the code is running as a web app.  It just seems strange to me that when I enable BetterLog, the onOpen function doesn't get called and the user menu to invoke the transfer to the second sheet doesn't show up (i.e. I get an execution error).

I will send you the code per separate email.

Thanks for looking into this!

Cheers, Markus

On 2020-03-24 12:24:46, Andrew Roberts <notifications@github.com> wrote:
There is nothing in your onOpen that would be opening a spreadsheet. You may have added some code that is global and outside any function that is trying to run whenever the sheet is open. You can share you code with me (andrew@roberts.net [mailto:andrew@roberts.net]) if you want me to take a quick look.

**Comment by profiVideos** [comment]
I'm going to close this issue as I can work around the issue.  I have since learned you need to add the line of code that invokes BetterLog in every function that will use it.  I had declared it once at the top of the file.
