### ISSUE TITLE
Giving permissions to spreadsheet file not working

### ISSUE THREAD

**Issue by flazouh** [peterherrmann/BetterLog#23]
When executing my google script:
function test(){
  Logger = BetterLog.useSpreadsheet('my id');
  Logger.log("test()")
}
I receive nothing in the spreadsheet, is that normal ? Do I need to set any permissions and if yes how ? =)

**Comment by flazouh** [comment]
found it, it was creating a new sheet that I didn't see =D my bad^^

**Comment by flazouh** [comment]
Ah, but now it doesn't work with:

function doPost(e) {
  Logger = BetterLog.useSpreadsheet('1esq4KsAvuaO6Dpg9NbPMNeGHg_0p38CsA3UshLmEBKo');
  Logger.log("doPost()")
  return ContentService.createTextOutput("done")
}

**Comment by KaiSpencer** [comment]
> Ah, but now it doesn't work with:
> 
> function doPost(e) {
> Logger = BetterLog.useSpreadsheet('1esq4KsAvuaO6Dpg9NbPMNeGHg_0p38CsA3UshLmEBKo');
> Logger.log("doPost()")
> return ContentService.createTextOutput("done")
> }

`Logger.log("doPost()")
`

Is the problem line.

doPost requires the params argument.

Try 

`Logger.log('Hello World')`

**Comment by andrewroberts** [comment]
Does the user that the doPost is deployed to run as have edit access to the GSheet "...BKo"?

And personally I'd try not assign it to Logger, as that could be causing some confusion somewhere...
