### ISSUE TITLE
My string is not using %s, but the error "Not enough arguments" appears

### ISSUE THREAD

**Issue by htadashi** [peterherrmann/BetterLog#24]
First of all, thanks for this very useful tool! 👍 

I don't know if it is really a bug, but I am getting the error "Not enough arguments" even without using "%s" in the log string. The code below reproduces the problem:

    function test_LOG(){
        const logger = BetterLog.useSpreadsheet(SPREADSHEET_KEY);
        let url = "https://api.stackexchange.com/2.2/search/excerpts/?body=every%20product%20may%20be%20added%20to%20existing%20category.%20I%20am%20trying%20to%20find%20a%20way%20to%20render%20page%20with%20products&order=desc&sort=creation&site=stackoverflow";   
        logger.log(url);
    }

**Comment by andrewroberts** [comment]
The library is picking up every instance of "%" as a placeholder for a
value (it's based on C's printf
<https://en.wikipedia.org/wiki/Printf_format_string>).

**Comment by htadashi** [comment]
@andrewroberts Thanks! Do you think it is a good idea to add a global option (such as the Logger.DATE_TIME_LAYOUT) to always ignore the placeholders?
