### ISSUE TITLE
Logging Html String not working

### ISSUE THREAD

**Issue by abhishekk728** [peterherrmann/BetterLog#25]
On logging `GmailMessage` class `getBody()` method:

It throws error:

`Error: Not enough arguments [line: 206, function: replacerDemuxer, file: format_string.js]`

**Comment by peterherrmann** [comment]
Hi, that function and file name are not from betterlog so not sure what
could be going on. If you can make a minimum line test case that reproduces
the problem that might help you narrow down the problem.

**Comment by smoofy** [comment]
Hello,

To reproduce:
```
  var response = UrlFetchApp.fetch('https://www.youtube.com');
  Logger.log(response.getContentText());
```

```
Error	
Error: Not enough arguments
replacerDemuxer	@ format_string.js.gs:206
formatString_	@ format_string.js.gs:215
```

**Comment by andrewroberts** [comment]
There is probably a percent placeholder - like %s - in the text, that the
printf function is expecting a variable value for.
