### ISSUE TITLE
Error using Better Log

### ISSUE THREAD

**Issue by garsone** [peterherrmann/BetterLog#6]
I have been successfully testing the Lirbrary for several days but as of today am getting the error
Error: Not enough arguments (line 134, file "Code", project "BetterLog")

---

PLease let me know the best approach to repair

Great tool by the Way

Gary

**Comment by peterherrmann** [comment]
That can happen if you call the log method without enough arguments. For example, this will cause the error:
`Logger.log("Test 1 2 %s")`
whereas this won't cause the error:
`Logger.log("Test 1 2 %s", "three")`

**Comment by garsone** [comment]
Thanks that makes sense
Is there a way  to not include due the time stamp in logger

Sent from Outlook Mobile

On Mon, May 9, 2016 at 1:26 PM -0700, "Peter Herrmann" notifications@github.com wrote:

That can happen if you call the log method without enough arguments. For example, this will cause the error:

Logger.log("Test 1 2 %s")

whereas this won't cause the error:

Logger.log("Test 1 2 %s", "three")

**Comment by peterherrmann** [comment]
I've added a how to example in the readme's Tips & Tricks:
https://github.com/peterherrmann/BetterLog/blob/master/README.md#tips--tricks
