### ISSUE TITLE
Permission Issue

### ISSUE THREAD

**Issue by jlanciers** [peterherrmann/BetterLog#7]
Hi,

When i include your library to my project,

![image](https://cloud.githubusercontent.com/assets/19395965/15302559/7edebd42-1b81-11e6-9019-bcadfe7cf355.png)

i've got this error when i run my script (my script is deployed as web app)

![image](https://cloud.githubusercontent.com/assets/19395965/15302596/bab42a14-1b81-11e6-8d2d-808b6b9ba563.png)

Thanks for you support.

JULIEN

**Comment by peterherrmann** [comment]
You may need to run one (any or an empty dummy) function in the IDE. This
will provoke the auth.

**Comment by jlanciers** [comment]
Hi Peter,

Solved by your solution :) 

I ran a random function in my IDE and script asked me for permission.

Thank you !
