### ISSUE TITLE
Cutting and Pasting BetterLog - have not been able to figure it out

### ISSUE THREAD

**Issue by MikeSchwartz** [peterherrmann/BetterLog#8]
Hi -

First, thank you very much for BetterLog. It's a great tool.

For security reasons I'm not able to use Libraries in my script. I'm using BetterLog as a library during development but will soon need to cut and paste it so that my scripts are self-contained. The instructions imply this is possible, but I haven't been able to figure out how. I am a complete noob at GAS and Javascript in general so I am probably missing something very simply.

Here's what I've done
- File -> New -> Project
- In that project, File -> New -> Script file
- Named the new file BetterLog.gs
- Cut-and-pasted https://raw.githubusercontent.com/peterherrmann/BetterLog/master/Code.gs into that file.
- Wrote the following test function in the project's Code.js file
  function testBetterLog() {
    Logger = BetterLog.useSpreadsheet("1v5PMxB1XomareGgLOjo9LNEuj6GNBdMjczJ3YnPra5Q");
    Logger.log("hello");
  }
- Saved both files
- Run
- Acknowledge the permissions
- Get the error: ReferenceError: "BetterLog" is not defined. (line 2, file "Code")

Please advise how I can use the source of BetterLog in my application.

Thanks again,
Mike

**Comment by andrewroberts** [comment]
You'll need to wrap all of the code in an object and modify the function definitions to use it locally. Note the commas after each function. In [the same way I've done it with the CBL library](https://script.google.com/d/1hkjXji3CyEKErC7HjAFcYULEir0yK0zLgqCz10yQB23OxfMPmF-bHxjL/edit?usp=drive_web). If you make a start I'll be happy to look it over:

```
var BetterLog = (function() {

return {

// Public Functions
.
.
.

info: function() {

},

} // return

// Private Functions
.
.
.

})() // BetterLog
```

**Comment by xentan** [comment]
I just pasted it in the same file i have been using for my project. And i pasted it first.

I then just did: var Logger = useSpreadsheet('my doc');

then i can freely use Logger.log("log me");

and it logs to my Log sheet.
